spring:
  application:
    name: ultistats
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

ultistats:
  persistence:
    path: ./data/ultistats.json
    interval: 30000
